In [8]:
import pandas as pd
    
#define the file paths
csv_file_path="C:\\Users\GodMode\Documents\\sample1.csv"
excel_file_path="C:\\Users\GodMode\Documents\\sample.xlsx"
#load the csv file
data_csv=pd.read_csv(csv_file_path)
print("csv file data:")
print(data_csv)

#load the excel file
data_excel=pd.read_excel(excel_file_path)
print("\n excel file data:")
print(data_excel)

#basic data exploration
print("\n data description:")
print("csv data description:")
print(data_csv.describe())
print("\n excel data description:")
print(data_excel.describe())

#displaying data types
print("\n data types in excel file:")
print(data_excel.dtypes)
print("\n data types in csv file:")
print(data_csv.dtypes)

print("dataset information:")
print(data_csv.info())

print("\n first few rows of the dataset:")
print(data_csv.head())
print("\n first few rows of the dataset:")
print(data_excel.head())

print("\n last few rows of the dataset:")
print(data_csv.tail())
print("\n last few rows of the dataset:")
print(data_excel.tail())

<>:4: SyntaxWarning: invalid escape sequence '\G'
<>:5: SyntaxWarning: invalid escape sequence '\G'
<>:4: SyntaxWarning: invalid escape sequence '\G'
<>:5: SyntaxWarning: invalid escape sequence '\G'
C:\Users\GodMode\AppData\Local\Temp\ipykernel_10744\108966381.py:4: SyntaxWarning: invalid escape sequence '\G'
  csv_file_path="C:\\Users\GodMode\Documents\\sample1.csv"
C:\Users\GodMode\AppData\Local\Temp\ipykernel_10744\108966381.py:5: SyntaxWarning: invalid escape sequence '\G'
  excel_file_path="C:\\Users\GodMode\Documents\\sample.xlsx"

csv file data:
      Name  Age  Score
0      sri   28     65
1     mary   21     87
2  florina   29     98

 excel file data:
     Name Course  Sem
0     ram    bca    1
1  seetha   bcom    3
2   deepa   bcom    4
3   pooja    bba    2
4   raghu    bba    6

 data description:
csv data description:
             Age      Score
count   3.000000   3.000000
mean   26.000000  83.333333
std     4.358899  16.802778
min    21.000000  65.000000
25%    24.500000  76.000000
50%    28.000000  87.000000
75%    28.500000  92.500000
max    29.000000  98.000000

 excel data description:
            Sem
count  5.000000
mean   3.200000
std    1.923538
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    6.000000

 data types in excel file:
Name      object
Course    object
Sem        int64
dtype: object

 data types in csv file:
Name     object
Age       int64
Score     int64
dtype: object
dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

 first few rows of the dataset:
      Name  Age  Score
0      sri   28     65
1     mary   21     87
2  florina   29     98

 first few rows of the dataset:
     Name Course  Sem
0     ram    bca    1
1  seetha   bcom    3
2   deepa   bcom    4
3   pooja    bba    2
4   raghu    bba    6

 last few rows of the dataset:
      Name  Age  Score
0      sri   28     65
1     mary   21     87
2  florina   29     98

 last few rows of the dataset:
     Name Course  Sem
0     ram    bca    1
1  seetha   bcom    3
2   deepa   bcom    4
3   pooja    bba    2
4   raghu    bba    6